services:
  - type: web
    name: locoro
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn locoro_app.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: locoro.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://locoro.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: locoro-db
          property: connectionString

databases:
  - name: locoro-db
    plan: free
