# Generated by Django 5.2.8 on 2025-12-03 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('is_smoking', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('base_price', models.DecimalField(decimal_places=0, help_text='通常時の基本料金（円）', max_digits=8)),
                ('status', models.CharField(choices=[('available', '空室（予約可）'), ('unavailable', '予約停止中'), ('occupied', '利用中'), ('cleaning', '清掃中'), ('holding', '予約中')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.hotel')),
            ],
            options={
                'ordering': ['hotel', 'room_number'],
                'unique_together': {('hotel', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='ReservationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('HOLD', '1時間予約中'), ('KEEPING', '30分キープ中'), ('EXPIRED', '期限切れ')], default='HOLD', max_length=20, verbose_name='予約ステータス')),
                ('hold_started_at', models.DateTimeField(auto_now_add=True, verbose_name='予約開始時刻')),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='1時間チケットの有効期限')),
                ('keep_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='30分キープの有効期限')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.room', verbose_name='部屋')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', '予約済み（清掃待ち）'), ('holding', 'キープ中'), ('checked_in', '利用中'), ('completed', '利用完了'), ('cancelled', 'キャンセル')], default='reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('extended_minutes', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
        ),
    ]
