# Generated by Django 5.2.8 on 2025-12-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', '空室（予約可）'), ('unavailable', '予約停止中'), ('occpied', '利用中'), ('cleaning', '清掃中'), ('holding', '予約中')], default='available', max_length=20),
        ),
    ]
