# Generated by Django 5.2.8 on 2025-12-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hold_started_at',
            field=models.DateTimeField(blank=True, help_text='キープ開始時刻（清掃完了時）', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='keep_expires_at',
            field=models.DateTimeField(blank=True, help_text='延長後の終了時刻', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, help_text='キープ終了時刻', null=True),
        ),
    ]
