# Generated by Django 5.2.8 on 2025-12-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', '空室（予約可）'), ('unavailable', '予約停止中'), ('occupied', '利用中'), ('cleaning', '清掃中'), ('holding', '予約中')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', '予約済み（清掃待ち）'), ('holding', 'キープ中'), ('checked_in', '利用中'), ('completed', '利用完了'), ('cancelled', 'キャンセル')], default='reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('extended_minutes', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
        ),
    ]
