# Generated by Django 5.2.8 on 2025-12-06 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation_hold_started_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'ホテル', 'verbose_name_plural': 'ホテル一覧'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '予約', 'verbose_name_plural': '予約一覧'},
        ),
        migrations.AlterModelOptions(
            name='reservationticket',
            options={'verbose_name': '予約チケット', 'verbose_name_plural': '予約チケット一覧'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['hotel', 'room_number'], 'verbose_name': '部屋', 'verbose_name_plural': '部屋一覧'},
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/', verbose_name='画像')),
                ('is_main', models.BooleanField(default=False, help_text='一覧などで優先的に表示したい画像ならチェック', verbose_name='メイン画像かどうか')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.room', verbose_name='部屋')),
            ],
            options={
                'verbose_name': '部屋画像',
                'verbose_name_plural': '部屋画像',
                'ordering': ['-is_main', 'id'],
            },
        ),
    ]
