# Generated by Django 5.2.8 on 2025-12-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation_hold_started_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'ホテル', 'verbose_name_plural': 'ホテル一覧'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '予約', 'verbose_name_plural': '予約一覧'},
        ),
        migrations.AlterModelOptions(
            name='reservationticket',
            options={'verbose_name': '予約チケット', 'verbose_name_plural': '予約チケット一覧'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['hotel', 'room_number'], 'verbose_name': '部屋', 'verbose_name_plural': '部屋一覧'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', '予約待ち'), ('holding', 'キープ中'), ('checked_in', '利用中'), ('completed', '利用完了'), ('cancelled', 'キャンセル')], default='reserved', max_length=20),
        ),
    ]
