# Generated by Django 5.2.8 on 2025-12-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hotel_options_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/', verbose_name='ホテル画像'),
        ),
    ]
