# Generated by Django 5.2.8 on 2025-12-06 17:47
from django.db import models, migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hotel_options_alter_reservation_options_and_more'),
    ]

    operations = [
          migrations.CreateModel(
            name="RoomImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="room_images/", verbose_name="画像")),
                ("is_main", models.BooleanField(default=False, help_text="一覧などで優先的に表示したい画像ならチェック", verbose_name="メイン画像かどうか")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="アップロード日時")),
                ("room", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="core.room", verbose_name="部屋")),
            ],
            options={
                "verbose_name": "部屋画像",
                "verbose_name_plural": "部屋画像",
                "ordering": ("-is_main", "id"),
            },
        ),
    ]
