# Generated by Django 5.2.8 on 2025-12-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_roomimage_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomimage',
            options={'ordering': ['-is_main', 'id'], 'verbose_name': '部屋画像', 'verbose_name_plural': '部屋画像'},
        ),
    ]
