# Generated by Django 5.2.8 on 2025-12-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hotel_image'),
        ('core', '0005_alter_roomimage_options'),
    ]

    operations = [
    ]
