# Generated by Django 5.2.8 on 2025-12-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_0004_hotel_image_0005_alter_roomimage_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='階数'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', '予約待ち'), ('holding', 'キープ中'), ('checked_in', '利用中'), ('completed', '利用完了'), ('cancelled', 'キャンセル')], default='reserved', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hotel', 'floor', 'room_number')},
        ),
    ]
